Added prettier rule

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,14 +1,20 @@
 #!/bin/bash
 
-# Capture the exit code of the ESLint command
-lint_exit_code=$?
-
 # Run the npm run format command to format the code
 echo "Running code checker..."
 npm run format
 
+# Capture the exit code of the ESLint command
+lint_exit_code=$?
+
 # Add the formatted changes to the staging area
 git add .
+
+# If ESLint returned an error, exit with the same status (non-zero)
+if [ $lint_exit_code -ne 0 ]; then
+  echo "Found errors. Please fix them before committing."
+  exit $lint_exit_code
+fi
 
 # If there were no changes to add, this means the code was already formatted, so we don't need to commit again.
 if [ -z "$(git status --porcelain)" ]; then
@@ -17,4 +23,4 @@ if [ -z "$(git status --porcelain)" ]; then
 fi
 
 # Exit with the same status as the ESLint check
-exit $lint_exit_code
+. "$(dirname -- "$0")/_/husky.sh"
